;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GOAP",NewTagName="GOAP_Test")
+GameplayTagRedirects=(OldTagName="GOAP.PlayerState.CurrentLocationn",NewTagName="GOAP.PlayerState.CurrentLocation")
+GameplayTagList=(Tag="GOAP.PlayerState.CurrentLocation",DevComment="")
+GameplayTagList=(Tag="GOAP.PlayerState.GoToLocation",DevComment="")
+GameplayTagList=(Tag="GOAP.PlayerState.HasLocation",DevComment="")
+GameplayTagList=(Tag="GOAP.WorldState",DevComment="")
+GameplayTagList=(Tag="GOAP.WorldState.AmmoCount",DevComment="")
+GameplayTagList=(Tag="GOAP.WorldState.Energy",DevComment="")
+GameplayTagList=(Tag="GOAP.WorldState.HasTarget",DevComment="")
+GameplayTagList=(Tag="WorldState",DevComment="")

